Update schemas pay, keyreg, keyregnontx
algorandfoundation/algo-models pull request #1
Opened 2023-10-05 10:30 UTC by ehanoc

# What
- Schema files
- AVJ
- Model validation through schemas
- Testing

2023-10-05 17:19 UTC, PhearZero requested changes
Everything is looking good 🕺🏼!

2023-10-05 17:19 UTC, PhearZero commented on lib/schemas/pay.transaction.json
> +      "type": "object",
We can add schemas for some of the `Uint8Array`'s to give them a more formal name. Since they are going to be reused heavily, it would be good to declare their own schema in a separate file. Some definitions can be collocated in the same spec if they are only used for that object.

Combining Schemas in AJV: https://ajv.js.org/guide/combining-schemas.html
Using Refs: https://json-schema.org/understanding-json-schema/structuring#dollarref

### Simple Example (definitions in same document):
```json
{
  "type": "object",
  "properties": {
    "complex": {
      "$ref": "#/$defs/Account"
    }
  },
  "$defs": {
    "Account": {
      "type": "object",
      "properties": {
        "0": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        }
      },
      "required": ["0"]
    }
  }
}
``` 

### Split example (external schema)
#### Complex.json
```json
{
  "title": "Complex",
  "type": "object",
  "properties":{
    "snd": { "$ref": "Address.json"}
  }
}
```
#### Acccount.json
```json
{
 "$id": "https://example.com/Address.json",
 "title": "Address"
 "type": "object",
  "properties": {
    "0": {
      "type": "integer",
      "minimum": 0,
      "maximum": 255
    }
  },
  "required": ["0"]
}
```

2023-10-05 19:37 UTC, PhearZero requested changes
The only other thing I can think of is `additionalProperties: false` on the objects

Refrence: https://json-schema.org/understanding-json-schema/reference/object#additional-properties

2023-10-06 08:40 UTC, ehanoc commented
> The only other thing I can think of is `additionalProperties: false` on the objects
> 
> Refrence: https://json-schema.org/understanding-json-schema/reference/object#additional-properties

I'm keeping this enabled as the "note" field in transactions can have dynamic size. Unless you know a way to spec it to check for that?

2023-10-06 13:37 UTC, PhearZero approved these changes

2023-10-06 13:40 UTC, merged